#!/bin/bash

rm /opt/karaf/firstboot


if [[ "${CLEAN_CACHE}" = "true" || "${CLEAN_CACHE}" = "TRUE" ]]
then
  rm -rf /opt/karaf/data/cache
fi

if [ ! -z "${FETCH_CUSTOM_URL}" ]
then
    if [ "${FETCH_CUSTOM_URL}" != "NONE" ]
    then
        wget ${FETCH_CUSTOM_URL} -P /opt/karaf/etc
    fi
fi

if [ ! -d "/opt/karaf/vol/etc" ]
then
   mkdir /opt/karaf/vol/etc
fi

if [ ! -d "/opt/karaf/vol/home" ]
then
   mkdir /opt/karaf/vol/home
fi

cp /opt/karaf/etc_original.tgz /opt/karaf/vol/


if [[ "${LINK_VOL_DEPLOY}" = "true" || "${LINK_VOL_DEPLOY}" = "TRUE" ]]
then
	
   if [ ! -d "/opt/karaf/vol/deploy" ]
   then
       mkdir /opt/karaf/vol/deploy 
   fi

   if [ -d "/opt/karaf/deploy" ]
   then
       rm -rf /opt/karaf/deploy
   fi

   ln -s /opt/karaf/vol/deploy /opt/karaf/deploy
fi

if [[ "${LINK_VOL_LOG}" = "true" || "${LINK_VOL_LOG}" = "TRUE" ]]
then

   if [ ! -d "/opt/karaf/vol/log" ]
   then
       mkdir /opt/karaf/vol/log
   fi

   if [ -d "/opt/karaf/data/log" ]
   then
       rm -rf /opt/karaf/data/log
   fi

   ln -s /opt/karaf/vol/log /opt/karaf/data/log
fi

if [[ "${LINK_VOL_TMP}" = "true" || "${LINK_VOL_TMP}" = "TRUE" ]]
then

   if [ ! -d "/opt/karaf/vol/tmp" ]
   then
       mkdir /opt/karaf/vol/tmp
   fi

   if [ -d "/opt/karaf/data/tmp" ]
   then
       rm -rf /opt/karaf/data/tmp
   fi

   ln -s /opt/karaf/vol/tmp /opt/karaf/data/tmp
fi

if [[ "${LINK_VOL_MSG_BROKER}" = "true" || "${LINK_VOL_MSG_BROKER}" = "TRUE" ]]
then

   if [ ! -d "/opt/karaf/vol/artemis" ]
   then
       mkdir /opt/karaf/vol/artemis
   fi

   if [ -d "/opt/karaf/data/artemis" ]
   then
       rm -rf /opt/karaf/data/artemis
   fi

   ln -s /opt/karaf/vol/artemis /opt/karaf/data/artemis
fi

if [ ! -z "${KARAF_INIT_COMMANDS}" ]
then
    if [ "${KARAF_INIT_COMMANDS}" != "NONE" ]
    then
        echo ${KARAF_INIT_COMMANDS} > /opt/karaf/bin/initcommands
        /opt/karaf/bin/installscript1  >> /opt/karaf/data/initcommands.log 2>&1 &
    fi
fi


if [ -f  /opt/karaf/vol/bin/initcommands ]
then
    /opt/karaf/bin/installscript2 >> /opt/karaf/data/initcommands.log 2>&1 &
fi

